/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Parse an Archflow DSL string and return the JSON IR. */
export declare function parseDsl(dsl: string): string
/** Render an Archflow DSL string directly to SVG. */
export declare function renderDsl(dsl: string): string
/** Render a JSON IR string to SVG. */
export declare function renderSvg(jsonIr: string): string
